---
- name: Step 1 - Obtain Entity IDs get current monitoring mode from each host
  hosts: all
  gather_facts: true

  tasks:
    - name: Resolve Hostname to Dynatrace Entity ID
      ansible.builtin.include_tasks:
        file: tasks/step1/resolve_entity_name_to_id.yml

    - name: Get Monitoring Mode of Host
      ansible.builtin.include_tasks:
        file: tasks/step1/get_current_monitoring_mode.yml


- name: Step 2 - Batch apply Monitoring Mode
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Batch Apply Monitoring Mode
      ansible.builtin.include_tasks:
        file: tasks/step2/batch_apply_monitoring_mode.yml


- name: Step 3 - Verify monitoring mode
  hosts: all
  gather_facts: false

  tasks:
    - name: Verify Monitoring Mode
      ansible.builtin.include_tasks:
        file: tasks/step3/verify_monitoring_mode.yml
      when: not dt_skip_host
